### ISSUE TITLE
Define Classes

### ISSUE THREAD

**Issue by eighthill** [eighthill/Slime_Mold_Simulation#4]
Think and collect ideas about the classes we need for the project.
We could also try and collect ideas for some functions already.

**Comment by Krabgalasch** [comment]
We shoud add main_classes file which contains all of our classes. Possible options could be:
-Agent
-Food source
-The area which gets populated by the agents and food
-GUI
    -Live GUI with sliders for different settings of the mold or food

**Comment by Isabelle-Gbl** [comment]
Issues #8 , #9  and #15 have been describing each of those classes.
I closed this Issue since those classes have been defined
