### ISSUE TITLE
Create Version 2.0 

### ISSUE THREAD

**Issue by Krabgalasch** [eighthill/Slime_Mold_Simulation#52]
We now have a prototype of our slime mold simulation.

The next steps are to improve the logic of our agents and the pathfinding.

![plan slime mold simulation](https://github.com/eighthill/Slime_Mold_Simulation/assets/40695202/659970a5-25f2-4720-be42-9d8bc29f5c99)

**Comment by Isabelle-Gbl** [comment]
documentation:
We decided to merge all of our current active branches so that we all get a better overview and understanding of the current status of the project.
