### ISSUE TITLE
Import Vispy in workflow for testing

### ISSUE THREAD

**Issue by ModusMorris** [eighthill/Slime_Mold_Simulation#6]
We need Vispy and modernGL in our Workflow to merg our stuff

**Comment by eighthill** [comment]
I am currently working on this issue on this branch: [workflow_tests](https://github.com/eighthill/Slime_Mold_Simulation/tree/workflow_tests)
Haven't found a solution yet to this error message but I'm looking further into it:
`WARNING: Could not load the Qt platform plugin "xcb" in "" even though it was found.`
